apiVersion: v1
kind: Secret
metadata:
  name: dockerhub.pushsecret
  namespace: workspace-creator
type: Opaque
stringData:
  config.json: |-
    auths:
      https://index.docker.io/v1/: 
        auth: "<password or token here>"
        email: "<email here>"  
