apiVersion: v1
kind: Secret
metadata:
  name: dockerhub.pushsecret
  namespace: workspace-creator
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username":"{{username}}",
          "password":"{{password}}"
        }
      }   
    }
