kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{galushka_name}}
  namespace: {{openshift_workspace_name}}
spec:
  output:
    to:
      kind: DockerImage
      {%set path_components = [output_docker_repo_url, galushka_name + ":" + docker_tagname]%}
      name: {{path_components|path_join}}
    pushSecret:
      name: dockerhub.pushsecret
  resources:
    limits:
      cpu: {{number_of_CPU_cores|default('2')}}
      memory: {{memory_allowed|default('1Gi')}}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{base_dockerimage}}
      env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: OPENSHIFT_SERVER_URL
          value: {{OPENSHIFT_SERVER_URL}}
        - name: OPENSHIFT_LOGIN_TOKEN
          value: {{OPENSHIFT_LOGIN_TOKEN}}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{source_git_repo_url}}
      ref: master
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github.secret
  runPolicy: Serial
